### ISSUE TITLE
Compiling the linux headers leads to package installation errors

### ISSUE THREAD

**Issue by jgsiqueira87** [DukeChocula/CM3588#1]
Before compiling the linux headers, an "apt update" is needed.

Additionally, build-kernel.sh tries to install python2 using apt, leading to an error (has no installation candidate).

**Comment by DukeChocula** [comment]
You actually can find the kernel headers at /opt/archives/linux-headers-6.1.57_6.1.57-11_arm64.deb

I will update my guide to reflect both the fix to the build-kernel.sh and the fact that they're precompiled.
